name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake8:
    name: Flake8 (Python ${{ matrix.python-version }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.10"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Check code with Flake8
        run: |
          # Check according to the config file.
          flake8 . --count --show-source --statistics

  black:
    name: Black
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Check code with Black
        uses: psf/black@stable
