name: Check Line Endings

on:
  - push
  - pull_request

jobs:
  crlf-check:
    name: Ensure there is no CRLF
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v2

      - name: Check endings (fail for CRLF, pass for LF)
        uses: erclu/check-crlf@v1
